apiVersion: apps/v1
kind: Deployment
metadata:
  name: mes-api
  labels:
    app.kubernetes.io/name: mes-api
    app.kubernetes.io/part-of: mes
    app.kubernetes.io/component: mes-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mes-api
  template:
    metadata:
      labels:
        app: mes-api
        app.kubernetes.io/part-of: mes
        app.kubernetes.io/component: mes-api
    spec:
      containers:
        - name: mes-api
          image: ghcr.io/codeserengetiorganization/mes-api:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: mes-api-config
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: mes-api-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mes-api-db-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mes-api-db-secret
                  key: SPRING_DATASOURCE_PASSWORD
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: mes-api-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: KAFKA_CONSUMER_GROUP_ID
              valueFrom:
                configMapKeyRef:
                  name: mes-api-config
                  key: KAFKA_CONSUMER_GROUP_ID
      imagePullSecrets:
        - name: mes-api-ghcr-secret
