apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mes-prod
resources:
  - mes-api-config.yaml
  - deployment.yaml
  - service.yaml
commonLabels:
  app.kubernetes.io/part-of: mes
  app.kubernetes.io/component: mes-api
