apiVersion: v1
kind: Service
metadata:
  name: mes-api-service
  labels:
    app.kubernetes.io/name: mes-api
    app.kubernetes.io/part-of: mes
    app.kubernetes.io/component: mes-api
spec:
  type: NodePort
  selector:
    app: mes-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30083
