apiVersion: v1
kind: Service
metadata:
  name: react-frontend-service
spec:
  type: NodePort
  selector:
    app: react-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30082 # React frontend (must be between 30000-32767)
