apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: eol-raw-data
  namespace: machine-monitoring
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 172800000  # 48 hours (48 * 60 * 60 * 1000)
    cleanup.policy: delete

