apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: machine-monitoring

# Kafka topic resources
# Apply this after Kafka cluster is ready
resources:
  - manufacturing-results-topic.yaml
  - manufacturing-failures-topic.yaml

