apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: manufacturing-failures-topic
  namespace: machine-monitoring
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 2592000000  # 30 days (30 * 24 * 60 * 60 * 1000)
    cleanup.policy: delete

